(include_subdirs unqualified)

(executable
 (name main)
 (public_name campfire-oxcaml)
 (modules main)
 (libraries campfire_oxcaml_core base cohttp-eio eio_main sqlite3 yojson))

(library
 (name campfire_oxcaml_core)
 (wrapped false)
 (modules bcrypt database)
 (foreign_stubs
  (language c)
  (names bcrypt_stubs bcrypt blf))
 (libraries sqlite3))

(test
 (name database_test)
 (modules database_test)
 (libraries campfire_oxcaml_core sqlite3))
